### PR TITLE
[LOCAL ONLY] Add passwordless login

### LINKED ISSUE #269: Login on locally running version does not work
I run Homebrewery locally without any issues except when I try to login. I get re-directed to the NaturalCrit.com login page. Should the login process be self-contained? I login into the Natural Crit page and I get re-directed to my local copy but the login has failed. How do I create logins locally?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

### PR DESCRIPTION
**Pull request by G-Ambatte**
This PR adds the ability to log in without a password on local installations only. It also implements a new global object `config` which - at the time of this PR - contains only the NODE_ENV (in property `environment`) and JWT token encoding secret key (in property `secret`).

This PR resolves #269.

### CODE REVIEW

**Comment by G-Ambatte** [comment]
@AlexeySachkov do you have any idea why this PR will only pass testing if the timeout of the first test is increased to more than 5s? It looks like it completed in just under 12s (https://app.circleci.com/pipelines/github/G-Ambatte/homebrewery/701/workflows/fde4f457-e058-48c5-8186-060061d9eca5/jobs/700)

I tried splitting out the test stage from the build stage (see https://app.circleci.com/pipelines/github/G-Ambatte/homebrewery?branch=experimental-CI_update) but even so, the first of the route tests takes about 5 or 6s to complete, while the rest complete in literally milliseconds.

Any thoughts? Is this related to the PR at all, or is this generalized testing weirdness???

**Comment by AlexeySachkov** [comment]
> @AlexeySachkov do you have any idea why this PR will only pass testing if the timeout of the first test is increased to more than 5s? It looks like it completed in just under 12s (https://app.circleci.com/pipelines/github/G-Ambatte/homebrewery/701/workflows/fde4f457-e058-48c5-8186-060061d9eca5/jobs/700)
> 
> I tried splitting out the test stage from the build stage (see https://app.circleci.com/pipelines/github/G-Ambatte/homebrewery?branch=experimental-CI_update) but even so, the first of the route tests takes about 5 or 6s to complete, while the rest complete in literally milliseconds.
> 
> Any thoughts? Is this related to the PR at all, or is this generalized testing weirdness???

I think it is generalized testing weirdness which has little to do with your PR, see #1982. It seems like tests takes forever to be initialized/set up and I don't know the exact reason for that. One of the reasons could be that modules loading is slow under `jest`, but I really doubt that your changes caused 2x slowdown - CI machine is likely a non-physical machine, which means that its performance could be unstable as well.

I think it should be ok to increase the timeout, but I suggest we do that globally through [jest config](https://jestjs.io/docs/configuration#testtimeout-number) in `package.json`:
https://github.com/naturalcrit/homebrewery/blob/c9935fa45ccc502ec0e454ee090471a9c88be2aa/package.json#L33-L39

**Comment by G-Ambatte** [comment]
> > @AlexeySachkov do you have any idea why this PR will only pass testing if the timeout of the first test is increased to more than 5s? It looks like it completed in just under 12s (https://app.circleci.com/pipelines/github/G-Ambatte/homebrewery/701/workflows/fde4f457-e058-48c5-8186-060061d9eca5/jobs/700)
> > I tried splitting out the test stage from the build stage (see https://app.circleci.com/pipelines/github/G-Ambatte/homebrewery?branch=experimental-CI_update) but even so, the first of the route tests takes about 5 or 6s to complete, while the rest complete in literally milliseconds.
> > Any thoughts? Is this related to the PR at all, or is this generalized testing weirdness???
> 
> I think it is generalized testing weirdness which has little to do with your PR, see #1982. It seems like tests takes forever to be initialized/set up and I don't know the exact reason for that. One of the reasons could be that modules loading is slow under `jest`, but I really doubt that your changes caused 2x slowdown - CI machine is likely a non-physical machine, which means that its performance could be unstable as well.
> 
> I think it should be ok to increase the timeout, but I suggest we do that globally through [jest config](https://jestjs.io/docs/configuration#testtimeout-number) in `package.json`:
> 
> https://github.com/naturalcrit/homebrewery/blob/c9935fa45ccc502ec0e454ee090471a9c88be2aa/package.json#L33-L39

Cool, I'll put it into a separate PR, probably tomorrow at this stage

**Comment by G-Ambatte** [comment]
I have removed the test timeout changes from this PR and raised #2094 to apply the timeout change globally as suggested. However, as the test still takes >5s to complete, it is now failing again. I am extremely confident that this PR will pass the tests once #2094 is merged.

File: server/app.js [hunk 1]
```diff
@@ -262,14 +262,26 @@ app.get('/print/:id', asyncHandler(async (req, res, next)=>{
...
+	// Create configuration object
+	const configuration = {
+		local       : false,
+		environment : config.get('node_env')
+	};
+	// Add local only items to configuration object
+	const localEnvironments = config.get('local_environments');
+	if(localEnvironments.includes(configuration.environment)){
+		configuration.local = true;
+		configuration.secret = config.get('secret');
```
Comment (calculuschild) [inline server/app.js:274]: We really shouldn't be passing `secret` along to the client browser. Even in this case where it's purely for local logins, I am wary of potential abuses of this in the future.

Instead, the `localLogin` function in `account.jsx` should send a request to the server. See the Naturalcrit Repo for an example: https://github.com/naturalcrit/naturalcrit/blob/6e62368f807596dcafcbd5bcad5181bce2982455/client/naturalcrit/account.actions.js#L5-L15

Even if we don't require a password, the login should still go through the server instead of exposing key variables to the browser.

File: server/app.js [hunk 2]
```diff
@@ -262,14 +262,26 @@ app.get('/print/:id', asyncHandler(async (req, res, next)=>{
...
 	const props = {
 		version     : require('./../package.json').version,
 		url         : req.originalUrl,
 		brew        : req.brew,
 		brews       : req.brews,
 		googleBrews : req.googleBrews,
 		account     : req.account,
-		enable_v3   : config.get('enable_v3')
+		enable_v3   : config.get('enable_v3'),
+		config      : configuration
```
[the remark this answers is not in the document]
Comment (G-Ambatte) [reply server/app.js:284]: My first thought was anything that gets pulled via `config.get()` - the only exception to this being `enable_v3` as I didn't want to mess with existing functionality.
However this could easily be extended to user configuration; the user's preferred default renderer, theme, etc. However while this change would lay the groundwork for such features, they are well outside the scope of this PR.

File: server/app.js (hunk 1 above)
Comment (G-Ambatte) [reply server/app.js]: This should now be implemented in today's changes.

File: client/homebrew/navbar/account.navitem.jsx [hunk 3]
```diff
@@ -28,7 +29,29 @@ const Account = createClass({
 		};
 	},
 
+	localLogin : async function(){
+		const username = prompt('Enter username:');
+		if(!username) {return;};
```
Comment (calculuschild) [inline client/homebrew/navbar/account.navitem.jsx:34]:
```suggestion
		if(!username) {return;}
```

File: client/homebrew/navbar/account.navitem.jsx [hunk 4]
```diff
@@ -28,7 +29,29 @@ const Account = createClass({
...
+		const expiry = new Date;
+		expiry.setFullYear(expiry.getFullYear() + 1);
+
+		const token = await request.post('/login')
+				.send({ username })
+				.then((response)=>{
+					return response.body;
+				})
+				.catch((err)=>{
+					return null;
```
Comment (calculuschild) [inline client/homebrew/navbar/account.navitem.jsx:45]:
```suggestion
					console.warn(err);
```

Comment (G-Ambatte) [reply client/homebrew/navbar/account.navitem.jsx]: Committed both suggested changes, and resolved the new merge conflict.

File: server/app.js [hunk 5]
```diff
@@ -259,9 +259,36 @@ app.get('/print/:id', asyncHandler(async (req, res, next)=>{
 	return next();
 }));
 
+const localEnvironments = config.get('local_environments');
+const nodeEnv = config.get('node_env');
```
Comment (calculuschild) [inline server/app.js:263]:
```suggestion
const nodeEnv = config.get('node_env');
const isLocalEnvironment = config.get('local_environments').includes(nodeEnv);
```

File: server/app.js [hunk 6]
```diff
@@ -259,9 +259,36 @@ app.get('/print/:id', asyncHandler(async (req, res, next)=>{
 	return next();
 }));
 
+const localEnvironments = config.get('local_environments');
+const nodeEnv = config.get('node_env');
+// Login
+app.post('/login', (req, res)=>{
+	// Local only
+	if(!localEnvironments.includes(nodeEnv)){
```
Comment (calculuschild) [inline server/app.js:267]:
```suggestion
	if(!isLocalEnvironment){

```

File: server/app.js [hunk 7]
```diff
@@ -259,9 +259,36 @@ app.get('/print/:id', asyncHandler(async (req, res, next)=>{
...
 //Render the page
 const templateFn = require('./../client/template.js');
 app.use((req, res)=>{
+	// Create configuration object
+	const configuration = {
+		local       : false,
+		environment : nodeEnv
+	};
+	// Add local only items to configuration object
+	if(localEnvironments.includes(nodeEnv)){
```
Comment (calculuschild) [inline server/app.js:290]:
```suggestion
	if(isLocalEnvironment){

```

File: server/app.js [hunk 8]
```diff
@@ -259,9 +259,36 @@ app.get('/print/:id', asyncHandler(async (req, res, next)=>{
...
+		configuration.local = true;
+	};
```
Comment (calculuschild) [inline server/app.js:292]:
```suggestion
	const configuration = {
		local       : isLocalEnvironment,
		environment : nodeEnv
	};
```

File: server/app.js [hunk 9]
```diff
@@ -259,9 +259,33 @@ app.get('/print/:id', asyncHandler(async (req, res, next)=>{
 	return next();
 }));
 
+const nodeEnv = config.get('node_env');
+const isLocalEnvironment = config.get('local_environments').includes(nodeEnv);
+// Login
+app.post('/login', (req, res)=>{
```
Comment (calculuschild) [inline server/app.js:265]: What do you think about renaming this route to `/localLogin` or something?

Comment (G-Ambatte) [reply server/app.js:265]: I've just been experimenting with renaming the route `/local/login` and wrapping it a `isLocalEnvironment` check - so the route shouldn't even get loaded in Production.

Comment (G-Ambatte) [reply server/app.js]: Pushed the commit now

**Comment by calculuschild** [comment]
Nice.... This is looking pretty good. As @jeddai said, we can look later at getting Google drive integration but that can be a separate PR. I think this is ready to merge?

**Comment by G-Ambatte** [comment]
I think we're good!

This one has been a bit of a journey, not least because it's in the top five oldest open issues.

**Review by calculuschild — APPROVED** [review]
