### PR TITLE
Fix QR code snippet when `brew.shareId` doesn't exist

### LINKED ISSUE #1710: Insert QR Code fails vs `/new` brew
On the `/new` brew editor page, the *Insert QR Code* snippet inserts this:

     {width:100px;mix-blend-mode:multiply}

Note the `undefined`. Entirely understandable how that happens .. but what do we do to fix?

Maybe detect the editor is on `/new` and a) use `SHARE-ID-HERE` instead of `undefined`, and maybe b) also insert `<!-- ATTENTION: You will need to insert your share id into the url above, once you do save this brew -->`.

### PR DESCRIPTION
**Pull request by G-Ambatte**
This PR modifies the snippet generator for the QR code to use the URL for the Homebrewery home page when a `shareId` does not currently exist.

This resolves #1710.

### CODE REVIEW

**Review by calculuschild — CHANGES_REQUESTED** [review]
Can you use `dedent` to clean up the formatting a little? (Instead of the plus signs concatenating everything)

**Review by calculuschild — CHANGES_REQUESTED** [review]
Oh shoot. I guess this does need to stay on a single line in the output. I misread.

Can you go back to not using dedent and put the plus signs back at the end of lines as needed so the output is one single line? That's my fault. Otherwise looks fine.

**Comment by G-Ambatte** [comment]
Reverted the `dedent` commit, so back to original now.

File: client/homebrew/editor/snippetbar/snippets/snippets.js [hunk 1]
```diff
@@ -55,7 +55,7 @@ module.exports = [
 				gen  : (brew)=>{
 					return `![]` +
 							`(https://api.qrserver.com/v1/create-qr-code/?data=` +
-							`https://homebrewery.naturalcrit.com/share/${brew.shareId}` +
+							`https://homebrewery.naturalcrit.com` + `${brew.shareId ? `/share/${brew.shareId}` : ''}` +
```
Comment (calculuschild) [inline client/homebrew/editor/snippetbar/snippets/snippets.js:58]:
```suggestion
							`https://homebrewery.naturalcrit.com${brew.shareId ? `/share/${brew.shareId}` : ''}` +
```

**Review by calculuschild — APPROVED** [review]

**Comment by calculuschild** [comment]
Thanks @G-Ambatte ! 🎉

**Comment by G-Ambatte** [comment]
Looks like it's working fine on the staging site!
