### PR TITLE
Get external link and scroll to element

### LINKED ISSUE #2820: External Direct link
I understand you can link to specific id attributes by doing the following:

`<a href="http://www.external-website.com/page#some-id">Link</a>`

but using that with a homebrewery share link just doesn't work, i get that is because the document is inside an iframe or because the page is not rendered before following the link, but is there a way around this?

### PR DESCRIPTION
**Pull request by 5e-Cleric**
This does work, not sure it is perfect.

Instead of having to catch the exact time of load finish of the pages, the function waits 100ms before scrolling.
for this instance, i think this is appropiate, and easier to deal with.

Tested this with 90+ page doc, works fine. Unsetting smooth scroll as it triggers lots of page loads.

Closes #2820 and duplicate #3505

to test, try any brew url + `#id`

### CODE REVIEW

**Comment by 5e-Cleric** [comment]
Now also works with page ids

**Comment by dbolack-ab** [comment]
How should this be tested?

**Comment by 5e-Cleric** [comment]
I'm guessing you will have a lot to say about the scrolling methods, cannot remember why i did it this way.

**Review by dbolack-ab — APPROVED** [review]
Works like a charm.  This is a brilliant add.

**Comment by G-Ambatte** [comment]
With the removal of PPR and globally unique IDs, could we skip scrolling to page and go directly to the element instead?

**Comment by dbolack-ab** [comment]
> With the removal of PPR and globally unique IDs, could we skip scrolling to page and go directly to the element instead?

We could, but I think scrolling to the page is the better idea and is consistent with the various link jumps we do

**Comment by G-Ambatte** [comment]
> the various link jumps we do

...which is also behaviour that can now be reconsidered in the light of full document rendering and globally unique IDs.

That's not to say that the current behaviour is not necessarily desirous, but rather that until now, we haven't actually had the option to consider anything else.
It might be out of scope for this PR, but it's probably worth considering at some stage.

**Comment by dbolack-ab** [comment]
> Do you mean rendering the iframe directly at that page?
> 
.....
> This PR is supposed to handle only url navigation into the page so that would make sense, specially with smooth scrolling disabled to prevent unnecessary renders. If you can point in the right direction i can try.

I firmly believe the current way is the right way. Stay page oriented.

**Comment by 5e-Cleric** [comment]
This could probably use the newest scrolling functions

File: client/homebrew/brewRenderer/brewRenderer.jsx [hunk 1]
```diff
@@ -76,9 +75,80 @@ const BrewRenderer = (props)=>{
...
 
-	useEffect(()=>{ // Unmounting steps
-		return ()=>{window.removeEventListener('resize', updateSize);};
+	useEffect(() => {
+		const locationHash = window.location.hash;
+		const iframe = document.getElementById('BrewRenderer');
+		
+		const pageIdRegex = /^#p\d+$/;
+		
+		const handleIframeLoad = () => {
```
Comment (calculuschild) [inline client/homebrew/brewRenderer/brewRenderer.jsx:84]: We already have a function that fire when the iFrame loads: `frameDidMount`

File: client/homebrew/brewRenderer/brewRenderer.jsx [hunk 2]
```diff
@@ -76,9 +75,80 @@ const BrewRenderer = (props)=>{
...
+				if (pageIdRegex.test(locationHash)) {
+					const pageNumber = parseInt(locationHash.slice(2));
+					scrollToPage(pageNumber - 1);
+				} else {
+					const elementId = locationHash.slice(1);
+					if (elementId) {
+						getPageContainingElement(elementId)
+							.then((pageNumber) => {
+								if (pageNumber !== -1) {
+									scrollToPage(pageNumber);
```
Comment (calculuschild) [inline client/homebrew/brewRenderer/brewRenderer.jsx:95]: Do we not want to just scroll to the element directly instead of the containing page? Would simplify logic.

File: client/homebrew/brewRenderer/brewRenderer.jsx [hunk 3]
```diff
@@ -76,9 +75,80 @@ const BrewRenderer = (props)=>{
...
+                if (pageNumber > pages.length) {
+                    console.log('page not found');
+                } else {
+                    pages[pageNumber].scrollIntoView({ block: 'start' });
+                }
+            }
+        }
+    };
+	
+	const getPageContainingElement = (elementId) => {
```
Comment (calculuschild) [inline client/homebrew/brewRenderer/brewRenderer.jsx:135]: If we really do want to get the parent page of the element, I believe we can just use:

`document.getElementById("theId").closest(".page")`

`.closest` grabs the nearest ancestor that matches a certain query.

**Comment by calculuschild** [comment]
Blocked by #3484 

There is some rearranging of the scrolling logic there that will interfere with this. When I get that one merged it should be more clear what changes might be needed for this PR.

File: client/homebrew/brewRenderer/brewRenderer.jsx (hunk 2 above)
Comment (5e-Cleric) [reply client/homebrew/brewRenderer/brewRenderer.jsx:95]: Myself i prefer scrolling to the container page, much more clean experience. But i am not 100% settled on that

Comment (dbolack-ab) [reply client/homebrew/brewRenderer/brewRenderer.jsx]: I have found scrolling to the page is REALLY annoying on big documents.

Comment (5e-Cleric) [reply client/homebrew/brewRenderer/brewRenderer.jsx]: my experience is different, but this change is not worth fighting over, will do this change

**Comment by calculuschild** [comment]
Studying this one a bit, `isMounted` is set to true the same time the initial page rendering is started, which means the iFrame is mounted but the pages inside might not actually be done rendering. I wonder if we can add a new state for "firstRenderComplete" or something, that gets set when `renderPages()` completes for the first time, and use that as the check to wait for scrolling.

**Comment by 5e-Cleric** [comment]
>  it seems rendering the pages is also waiting for isMounted to be true

Aaah that explains it then...

I'll try, not sure

**Comment by ericscheid** [comment]
Maybe set up a `MutationObserver`?

```js
    const hash = window.location.hash;
    if (hash && iframeDoc) {
      const anchor = iframeDoc.querySelector(hash);

      if (anchor) {
        anchor.scrollIntoView();
      } else {
        // Use MutationObserver to wait for the element if it's not immediately available
        const observer = new MutationObserver((mutations, obs) => {
          const anchorElement = iframeDoc.querySelector(hash);
          if (anchorElement) {
            anchorElement.scrollIntoView();
            obs.disconnect(); // Stop observing once the element is found
          }
        });

        observer.observe(iframeDoc, {
          childList: true,
          subtree: true,
        });
```

**Comment by 5e-Cleric** [comment]
> Maybe set up a `MutationObserver`?
> 
> ```js
>     const hash = window.location.hash;
>     if (hash && iframeDoc) {
>       const anchor = iframeDoc.querySelector(hash);
> 
>       if (anchor) {
>         anchor.scrollIntoView();
>       } else {
>         // Use MutationObserver to wait for the element if it's not immediately available
>         const observer = new MutationObserver((mutations, obs) => {
>           const anchorElement = iframeDoc.querySelector(hash);
>           if (anchorElement) {
>             anchorElement.scrollIntoView();
>             obs.disconnect(); // Stop observing once the element is found
>           }
>         });
> 
>         observer.observe(iframeDoc, {
>           childList: true,
>           subtree: true,
>         });
> ```

Won't this trigger for every rerender of the preview?

**Comment by ericscheid** [comment]
> Won't this trigger for every rerender of the preview?

ahem .. 
> `            obs.disconnect(); // Stop observing once the element is found`

So .. on page load it looks for the element corresponding to `window.location.hash`. If that target does not yet exist, then the MutationObserver is created. When it gets triggered it scrolls to it, and then deletes the observer. Subsequent rerenders are not observed, and so no further scrolling occurs.

**Comment by 5e-Cleric** [comment]
This should be ready for merge

**Review by dbolack-ab — CHANGES_REQUESTED** [review]
When I select an out of bounds page, this sends me to Vault instead of the Brew.

I think this should instead go to the first or last page and provide an error message.

**Review by dbolack-ab — APPROVED** [review]
Previously reported error was in the testing, not the results.

**Comment by calculuschild** [comment]
Ok, just cleaned up a bit. Merging now!

Thanks @5e-Cleric ! 💯 ⭐ 🎉
